apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ include "web-server.fullname" . }}
  labels:
    {{- include "web-server.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  host: web-server
  subsets:
    - name: v1
      labels:
        app: web-server
        version: "{{ .Chart.AppVersion }}"

