apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "web-server.fullname" . }}
  labels:
    {{- include "web-server.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    istio: public-ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - 'www.case-study.internal'
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: web-server-credential
    hosts:
    - 'www.case-study.internal'

    # tls:
    #   httpsRedirect: false
