{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "web-server.serviceAccountName" . }}
  labels:
{{ include "web-server.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
