apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "web-server.fullname" . }}
  labels:
    {{- include "web-server.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
    - "{{ .Values.dns}}"
  gateways:
    - {{ include "web-server.fullname" . }}
  http:
    - match:
        - uri:
            prefix: "/"
      route:
        - destination:
            host: web-server
            port:
              number: 80
            subset: v1
      timeout: 15s
      retries:
        attempts: 3
        perTryTimeout: 5s


