---
  - name: Set SELinux policy to enforcing
    selinux:
      policy: targeted
      state: enforcing

  - name: Allow Apache to make network connections on SELinux
    become: true
    seboolean:
      name: httpd_can_network_connect
      state: yes
      persistent: yes
    notify: restart apache

  - name: Ensure firewalld is running
    service:
      name: firewalld
      state: started
      enabled: yes

  - name: Allow HTTP
    firewalld:
      service: http
      permanent: yes
      immediate: yes
      state: enabled

  - name: Allow HTTPS
    firewalld:
      service: https
      permanent: yes
      immediate: yes
      state: enabled

